NeutronAdminBundle_dashboard:
    pattern:  /
    defaults: { _controller: NeutronAdminBundle:Default:index }
    
NeutronAdminBundle_category:
    pattern:  /category
    defaults: { _controller: neutron_admin.controller.category:indexAction }
    
NeutronAdminBundle_category_create:
    pattern:  /category/create/{parentId}
    defaults: { _controller: neutron_admin.controller.category:createAction }

